// === fluxai.js ===
const axios = require("axios");

module.exports = {
  pattern: "fluxai",
  desc: "Generate an image using AI (Flux).",
  category: "ai",
  react: "🚀",
  filename: __filename,
  use: ".fluxai <prompt>",

  execute: async (conn, mek, m, { from, reply, q }) => {
    try {
      if (!q) return reply("⚠️ Please provide a prompt for the image.");

      await reply("> ⏳ Creating Flux AI image...");

      // GiftedTech Flux Image API
      const apiUrl = `https://api.giftedtech.co.ke/api/ai/fluximg?apikey=gifted&prompt=${encodeURIComponent(q)}`;

      const { data } = await axios.get(apiUrl);

      // Validate response
      if (!data || !data.success || !data.result) {
        console.error("[fluxai.js] Invalid API response:", data);
        return reply(`⚠️ Couldn’t generate image.\n📝 API Response: ${JSON.stringify(data)}`);
      }

      // Send reaction
      await conn.sendMessage(from, {
        react: { text: "🚀", key: mek.key }
      });

      // Send image back
      await conn.sendMessage(
        from,
        {
          image: { url: data.result },
          caption: `💸 *Image Generated by FluxAI* 🚀\n✨ Prompt: *${q}*`
        },
        { quoted: mek }
      );

    } catch (error) {
      console.error("[FluxAI Error]", error);

      let errMsg = "⚠️ An error occurred while generating the image.";
      if (error.response?.data) {
        errMsg += `\n\n📝 API Response: ${JSON.stringify(error.response.data)}`;
      } else if (error.code === "ECONNREFUSED" || error.code === "ENOTFOUND") {
        errMsg += "\n\n🌐 Connection error. API might be down.";
      } else {
        errMsg += `\n\nError: ${error.message}`;
      }

      reply(errMsg);
    }
  }
};
