const axios = require('axios');

module.exports = {
    pattern: "flux",
    desc: "Generate AI image using Flux",
    category: "ai",
    react: "🎨",
    filename: __filename,
    use: "<prompt>",

    execute: async (conn, message, m, { from, reply, q }) => {
        try {
            if (!q) {
                return reply(`🎨 *Flux AI Image Generator*\n\nUsage: ${PREFIX}flux <prompt>\n\nExample: ${PREFIX}flux beautiful landscape sunset`);
            }
            
            // React with processing emoji
            await conn.sendMessage(from, {
                react: { text: "⏳", key: message.key }
            }).catch(() => {});
            
            await reply(`🎨 *Generating AI image...*\n\nPrompt: "${q}"`);
            
            const response = await axios.get(`https://api.bk9.dev/ai/fluximg?q=${encodeURIComponent(q)}`, {
                timeout: 30000
            });
            
            if (response.data.status && response.data.result) {
                await conn.sendMessage(from, {
                    image: { url: response.data.result },
                    caption: `*╭━━━〔 🎨 𝙰𝙸 𝙸𝙼𝙰𝙶𝙴 〕━━━┈⊷*\n*┃🎨│ 𝙿𝚁𝙾𝙼𝙿𝚃 :❯ ${q}*\n*╰━━━━━━━━━━━━━━━┈⊷*\n\n🎨 *Generated by Flux AI*\n📱 *Powered by Tracle-Lite*`
                }, { quoted: message });
                
                // React with success emoji
                await conn.sendMessage(from, {
                    react: { text: "✅", key: message.key }
                }).catch(() => {});
                
            } else {
                await reply(`❌ *Failed to generate image!*\n\nPlease try another prompt or check API status.`);
                
                // React with error emoji
                await conn.sendMessage(from, {
                    react: { text: "❌", key: message.key }
                }).catch(() => {});
            }
            
        } catch (error) {
            console.error("Flux AI error:", error);
            await reply(`❌ *AI service error!*\n\nError: ${error.message}\n\nPlease try again later.`);
            
            // React with error emoji
            await conn.sendMessage(from, {
                react: { text: "❌", key: message.key }
            }).catch(() => {});
        }
    }
};