// === topdf.js ===
const fs = require("fs");
const PDFDocument = require("pdfkit");

module.exports = {
  pattern: "topdf",
  desc: "Convert text into a PDF locally 📄",
  category: "tools",
  react: "📄",
  filename: __filename,
  use: ".topdf <text> or reply to a message",

  execute: async (conn, mek, m, { from, reply, args }) => {
    try {
      // Get text from args or quoted message
      let text = args.join(" ");
      if (!text && m.quoted && m.quoted.text) {
        text = m.quoted.text;
      }

      if (!text) {
        text = "This PDF was generated by Tracle-lite 📄";
      }

      await reply("> 📝 Creating PDF...");

      // Create PDF file
      const doc = new PDFDocument();
      const filePath = `./gifted_${Date.now()}.pdf`;
      const stream = fs.createWriteStream(filePath);
      doc.pipe(stream);

      doc.fontSize(16).text(text, { align: "left" });
      doc.end();

      stream.on("finish", async () => {
        await conn.sendMessage(
          from,
          {
            document: { url: filePath },
            fileName: "Tracle-Lite.pdf",
            mimetype: "application/pdf",
          },
          { quoted: mek }
        );

        fs.unlinkSync(filePath); // cleanup
      });

    } catch (e) {
      console.error("[topdf.js]", e.message);
      reply("⚠️ Error generating PDF.");
    }
  },
};
